### ISSUE TITLE
Milestone 1 Tasks

### ISSUE THREAD

**Issue by mmyz88** [UBC-MDS/pytweet#1]
Just a rundown of [milestone1.md](https://github.ubc.ca/MDS-2020-21/DSCI_524_collab-sw-dev_students/blob/master/materials/materials/assignments/milestone1.md). Feel free to add

- [x] work contract
- [x] pick topic
- [x] create repo structure
- [x] name the repo/package
- [x] MIT license
- [x] add to `CONTRIBUTORS.md`
- [x] ~~edit `CONDUCT.md`~~ (just use the default one)
- [x] ~~agree upon a collaboration strategy and write it in `CONTRIBUTING.md`~~ (use default)
- [x] `README.md` write up
- [x] function specs and stubs (4/4)
- [x] create an issue for each function, assign writer
- [x] create project boards and link tasks to issues
- [x] submission

**Comment by huan-ds** [comment]
I opened a PR for "README.md write up". #3 Please feel free to change it.
