### ISSUE TITLE
Milestone 2: function tests and implementation

### ISSUE THREAD

**Issue by mmyz88** [UBC-MDS/pytweet#19]
Milestone 2 tasks related to our python package:

- [x] write tests for each function 
- [ ] implement function bodies
- [x] go back to tests to write more test, then back to code, 
- [x] make sure our functions handle exceptions

(don't worry about checking these boxes, just follow up in each of our own's function issue)
